#### general settings
name: 006_EDVRTSA_CA_scratch_lr1e-4_600k_REDS_LrCAR4S
use_tb_logger: true
model: video_base
distortion: sr
scale: 4
gpu_ids: [0,1,2,3]

#### datasets
datasets:
  train:
    name: REDS
    mode: REDS
    interval_list: [1]
    random_reverse: false
    border_mode: false
    dataroot_GT: /harddrives/beta/lbxie/VSR_datasets/REDS/train_sharp_wval.lmdb
    dataroot_LQ: /harddrives/beta/lbxie/VSR_datasets/REDS/train_sharp_bicubic_wval.lmdb
    cache_keys: REDS_trainval_keys.pkl

    N_frames: 5
    use_shuffle: true
    n_workers: 3  # per GPU
    # batch_size: 64
    batch_size: 32
    GT_size: 256
    LQ_size: 64
    use_flip: true
    use_rot: true
    color: RGB
  val:
    name: REDS4
    mode: video_test
    dataroot_GT: /harddrives/beta/lbxie/VSR_datasets/REDS4/GT
    dataroot_LQ: /harddrives/beta/lbxie/VSR_datasets/REDS4/sharp_bicubic
    cache_data: True
    N_frames: 5
    padding: new_info

#### network structures
network_G:
  which_model_G: EDVR
  nf: 128
  nframes: 5
  groups: 8
  basic_RBs: ResidualBlock_noBN_CA
  front_RBs: 5
  back_RBs: 30
  predeblur: false
  HR_in: false
  w_TSA: True


#### path
path:
  pretrain_model_G: ~
  strict_load: true
  resume_state: ~

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 1e-4
  lr_scheme: CosineAnnealingLR_Restart
  beta1: 0.9
  beta2: 0.99
  niter: 600000
  warmup_iter: -1  # -1: no warm up
  T_period: [150000, 150000, 150000, 150000]
  restarts: [150000, 300000, 450000]
  restart_weights: [1, 1, 1]
  eta_min: !!float 1e-7

  pixel_criterion: cb
  pixel_weight: 1.0
  val_freq: !!float 5e3

  manual_seed: 0

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
